# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b604a205f2580d20a12d89d09398be1605050508ba9f910962502e63259cb7b64286eceea4168717d9f464287fab9093b9a8310527342a58fdf19eebad261f5d

test:
  secret_key_base: e638920db91aeac85612c8a74f666b88c282b89ddec1e9646e560f940e30b857594657cddfa04079f231571f558bbfab10900c55e3da15fb37db30e8c74098c3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
